apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260619-014612-ksr980ki7hkt-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260619-014612-ksr980ki7hkt.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260619-014612-ksr980ki7hkt-service
            port:
              number: 80
