apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260619-014612-ksr980ki7hkt-service
spec:
  selector:
    app: enterprise-system-20260619-014612-ksr980ki7hkt
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
